
CREATE TABLE dev.CLIENTE_PJ
(	"CNPJ" NUMBER(*,0) NOT NULL ENABLE,
     "RAZAOSOCIAL" VARCHAR2(100 BYTE) NOT NULL ENABLE,
     "NOMEFANTASIA" VARCHAR2(100 BYTE) NOT NULL ENABLE,
     CONSTRAINT CLIENTE_PJ_PK PRIMARY KEY ("CNPJ")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "SYSTEM"  ENABLE,
     CONSTRAINT CLIENTE_PJ_FK FOREIGN KEY ("CNPJ")
         REFERENCES dev.CLIENTE ("ID_CLIENTE") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

