
CREATE TABLE dev.CONTA
(	"NUMERO" NUMBER NOT NULL ENABLE,
     "SALDO_ATUAL" NUMBER(10,2) NOT NULL ENABLE,
     "CLIENTE" NUMBER(*,0) NOT NULL ENABLE,
     "TIPO_CONTA" VARCHAR2(20 BYTE),
     CONSTRAINT CONTA_PK PRIMARY KEY ("NUMERO")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE SYSTEM  ENABLE,
     CONSTRAINT CLIENTE_FK FOREIGN KEY ("CLIENTE")
         REFERENCES dev.CLIENTE ("ID_CLIENTE") ON DELETE CASCADE ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE OR REPLACE TRIGGER dev.AJUSTESALDO AFTER INSERT OR UPDATE ON CONTA
                                                                  FOR EACH ROW

DECLARE

diferenca_sald number;
BEGIN

    diferenca_sald := :NEW.saldo_atual - :OLD.saldo_atual;
    IF(:OLD.saldo_atual = NULL) THEN
     INSERT INTO CONTA_LOG(numero,saldo_anterior,novo_saldo,tipo_movimentacao,diferenca_saldo) VALUES (:NEW.numero,0,:NEW.saldo_atual,:NEW.tipo_conta,diferenca_sald);


ELSE
         INSERT INTO CONTA_LOG(numero,saldo_anterior,novo_saldo,tipo_movimentacao,diferenca_saldo) VALUES (:NEW.numero,:OLD.saldo_atual,:NEW.saldo_atual,:NEW.tipo_conta,diferenca_sald);

END IF;



END ajusteSALDO;
/
ALTER TRIGGER dev.AJUSTESALDO ENABLE;

