
CREATE TABLE dev.ENDERECO
(	"ID_ENDERECO" NUMBER NOT NULL ENABLE,
     "CEP" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "BAIRRO" VARCHAR2(50 BYTE) NOT NULL ENABLE,
     "UF" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "CIDADE" VARCHAR2(25 BYTE),
     "CASA" NUMBER,
     CONSTRAINT ENDERECO_PK PRIMARY KEY ("ID_ENDERECO")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "SYSTEM"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

