CREATE TABLE dev.MOVIMENTACAO
(	"ID" NUMBER(*,0) NOT NULL ENABLE,
     "VALOR" NUMBER(10,2) NOT NULL ENABLE,
     "DESCRICAO" VARCHAR2(25 BYTE) NOT NULL ENABLE,
     "CONTA" NUMBER(*,0) NOT NULL ENABLE,
     CONSTRAINT MOVIMENTACAO_PK PRIMARY KEY ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "SYSTEM"  ENABLE,
     CONSTRAINT MOVIMENTACAO_CONTA_NUMERO_FK FOREIGN KEY ("CONTA")
         REFERENCES dev.CONTA ("NUMERO") ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE OR REPLACE TRIGGER dev.FAZERMOVIMENTACAO before INSERT ON MOVIMENTACAO
FOR EACH ROW


DECLARE
calculo   number(10, 2);
    v_saldo_atual number(10, 2);

BEGIN

BEGIN
select c.saldo_atual
into v_saldo_atual
from conta c
where c.numero = :NEW.conta;
end;

     if (:NEW.descricao = 'DEPOSITO') then

     calculo  := v_saldo_atual + :NEW.valor;
else
      calculo  := v_saldo_atual - :NEW.valor;
end if;

begin
update conta en
set en.saldo_atual =calculo
where en.numero = :NEW.conta;
end;




END fazerMovimentacao;
/
ALTER TRIGGER dev.FAZERMOVIMENTACAO ENABLE;

